version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore CodeIt/CodeIt.sln
build:
  project: CodeIt/CodeIt.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: 9wExykceXL/o/hVhwWR7QzOZZLLBlShMLhN0C7p3MOeqBO8u/8QEfeRfmwzODhhu
    
after_test:
  - CodeIt\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"CodeIt\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single CodeIt\CodeIt.UnitTests\bin\Debug\CodeIt.UnitTests.dll" -output:cover.xml

  - CodeIt\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml